### ISSUE TITLE
disappearing items

### ISSUE THREAD

**Issue by pbobbert** [cbrl/ShrineOfDisorder#1]
The default value of false for these four config options causes a bug where upon activating the shine of disorder, it will remove all the items of said categories from your in game visible list of items --- but you will still benefit as if you had them. Setting the values to true seems to have correct behavior from my testing. No other config settings were altered.

LunarItems, VoidItems, BossItems, VoidBossItems

**Comment by cbrl** [comment]
Good catch. I'm fairly certain this is due to the `self.itemAcquisitionOrder.clear()` calls on these lines:

https://github.com/cbrl/ShrineOfDisorder/blob/6c7a7f83a500f4355943f7298f05e707e88d4810/ShrineOfDisorder/ShrineOfDisorder.cs#L296

https://github.com/cbrl/ShrineOfDisorder/blob/6c7a7f83a500f4355943f7298f05e707e88d4810/ShrineOfDisorder/ShrineOfDisorder.cs#L321

Instead of clearing the entire acquisition order, only the items belonging to enabled tiers should be removed. I'll put in a fix when I have some down time. Until then, I believe it should only have a visual side effect, as you mentioned.

**Comment by cbrl** [comment]
Fixed with commit 1f55156525cc4d74ab1f98c6ab9ae36c10d643f2, and updated on Thunderstore,
